<?php if ($this->errors) :?>
<div class="initform" id="initform">
	<div class="alert alert-error hidden" id="form-error-messages">
		<button type="button" class="close" data-dismiss="alert">×</button>
		<p id="my-error-messages"></p>
	</div>
	
	<h3>RECURSO PROTEGIDO/h3>
	
	<?php echo $this->form?>
	
</div>
<?php else:?>
<div class="container-fluid mywhite">
	<div class="row-fluid">
		<div class="span12 ">
		    <?php if (count($this->records) > 0):?>
		    <h3><i class="icon-file-alt"></i> Listagem</h3>
			<table class="table table-striped txtsmall">
				<tr>
					<th><i class="icon-list-alt"></i> Nº</th>
					<th><i class="icon-user"></i> Nome</th>
					<th><i class="icon-cogs"></i> Secção</th>
					<th><i class="icon-calendar"></i> Data</th>
					<?php if ($this->admin == 0):?>
					<th><i class="icon-edit"></i> Editar</th>
					<?php endif;?>
					<?php if ($this->admin == 1):?>
					<th><i class="icon-check"></i> Administração</th>
					<?php endif;?>
				</tr>
			     <?php foreach ($this->records as $record):?>
			    <tr>
			        <td><?=$record['num'];?></td>
			        <td><?=$record['nome'];?></td>
			        <td><?=$record['seccao'];?></td>
			        <td><?=$record['data_inicio'];?></td>
			        <?php if ($this->admin == 0):?>
			        <td><a href="/edit/normal/<?=$record['id'];?>" class="btn btn-small btn-primary">Editar</a></td>
			        <?php endif;?>
			        <?php if ($this->admin == 1):?>
					<td><a href="/edit/admin/<?=$record['id'];?>" class="btn btn-small btn-success">Editar</a></td>
					
					<?php endif;?>
				</tr>
			    <?php endforeach;?>
			    
			</table>
			
			<?php else:?>
	             <p>&nbsp;</p>
	            <?=$this->Flashinfo('info', 'Não existe nenhum boletim para esta data.');?>
	        <?php endif;?>
		</div>
	</div>
</div>
<?php endif;?>